from __future__ import annotations

import hashlib
import html
import json
import re
import shutil
import struct
import subprocess
import tempfile
import zlib
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image


AI_PATTERNS: list[tuple[str, str, str, str, int]] = [
    ("TC260 AIGC 标识", r"\btc260:aigc\b|tc260\.org\.cn/ns/aigc|(?:\"|&quot;)Label(?:\"|&quot;)\s*:\s*(?:\"|&quot;)1(?:\"|&quot;)", "metadata", "发现 TC260 AIGC 元数据标识，表示该文件被标记为 AI 生成/AI 合成内容。", 90),
    ("Stable Diffusion", r"\bnegative prompt\b|\bsteps:\s*\d+|\bsampler:\b|\bsd(?:xl)?\b", "metadata", "发现 Stable Diffusion 风格的生成参数。", 70),
    ("ComfyUI", r"\bcomfyui\b|\"class_type\"\s*:\s*\"(?:ksampler|checkpointloadersimple)\"|\bksampler\b", "metadata", "发现 ComfyUI 工作流或节点元数据。", 75),
    ("AUTOMATIC1111", r"\bautomatic1111\b|\ba1111\b|\bclip skip\b|\bhires(?:\.| )fix\b", "metadata", "发现 AUTOMATIC1111 生成参数。", 70),
    ("Midjourney", r"\bmidjourney\b|\b--ar\s+\d+:\d+|\b--v\s+\d", "metadata", "发现 Midjourney 标记或提示词参数。", 65),
    ("DALL-E / OpenAI", r"\bdall[ -]?e\b|\bopenai\b|\bgpt-image\b", "metadata", "发现 OpenAI 图像生成标记。", 70),
    ("Adobe Firefly", r"\badobe firefly\b|\bfirefly\b", "metadata", "发现 Adobe Firefly 标记。", 70),
    ("NovelAI", r"\bnovelai\b|\buc preset\b|\bsteps\b.*\bscale\b.*\bseed\b", "metadata", "发现 NovelAI 风格生成参数。", 65),
    ("InvokeAI", r"\binvokeai\b|\binvoke ai\b", "metadata", "发现 InvokeAI 标记。", 70),
    ("Leonardo AI", r"\bleonardo\.?ai\b|\bleonardo ai\b", "metadata", "发现 Leonardo AI 标记。", 65),
    ("Ideogram", r"\bideogram\b", "metadata", "发现 Ideogram 标记。", 65),
    ("Canva AI", r"\bmagic media\b|\bcanva ai\b", "metadata", "发现 Canva AI 标记。", 55),
]

VISIBLE_WATERMARK_PATTERNS: list[tuple[str, str]] = [
    ("OpenAI", r"\bopenai\b|\bdall[ -]?e\b"),
    ("Midjourney", r"\bmidjourney\b"),
    ("Adobe Firefly", r"\bfirefly\b"),
    ("Stable Diffusion", r"\bstable diffusion\b"),
    ("Generated by AI", r"\bgenerated by ai\b|\bai generated\b|\bcreated with ai\b"),
]


def analyze_file(
    path: str | Path,
    enable_ocr: bool = False,
    artifacts_dir: str | Path | None = None,
    content_assessment: dict[str, Any] | None = None,
) -> dict[str, Any]:
    image_path = Path(path).expanduser().resolve()
    data = image_path.read_bytes()
    image_info = _read_image_info(image_path)
    metadata = _extract_metadata(data, image_path)
    embedded_signals = _embedded_signals(data)
    ai_indicators: list[dict[str, Any]] = []

    if embedded_signals["c2pa_present"]:
        ai_indicators.append(
            {
                "kind": "content_credentials",
                "generator": "C2PA / Content Credentials",
                "source": "binary_scan",
                "confidence": 90,
                "reason": "在文件字节中发现 C2PA/JUMBF 内容凭证标记。",
                "sample": embedded_signals["c2pa_sample"],
            }
        )

    text_sources = _collect_text_sources(metadata, data)
    ai_indicators.extend(_scan_ai_text_sources(text_sources))

    visible_watermarks = {"ocr_available": bool(shutil.which("tesseract")), "ocr_enabled": enable_ocr, "matches": [], "text": ""}
    if enable_ocr:
        visible_watermarks = _run_ocr(image_path)
        for match in visible_watermarks["matches"]:
            ai_indicators.append(
                {
                    "kind": "visible_watermark",
                    "generator": match["generator"],
                    "source": "ocr",
                    "confidence": 55,
                    "reason": "OCR 识别到常见 AI 水印或生成器可见文字。",
                    "sample": match["text"],
                }
            )

    artifacts = {}
    if artifacts_dir is not None:
        out_dir = Path(artifacts_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        spectrum_path = out_dir / f"{image_path.stem}-fft-spectrum.png"
        if _write_frequency_artifact(image_path, spectrum_path):
            artifacts["frequency_spectrum"] = str(spectrum_path)

    result = {
        "file": {
            "path": str(image_path),
            "name": image_path.name,
            "size_bytes": image_path.stat().st_size,
            "sha256": hashlib.sha256(data).hexdigest(),
        },
        "image": image_info,
        "metadata": metadata,
        "embedded_signals": embedded_signals,
        "visible_watermarks": visible_watermarks,
        "ai_indicators": _dedupe_indicators(ai_indicators),
        "content_assessment": _normalize_content_assessment(content_assessment),
        "forensic_notes": _forensic_notes(),
        "artifacts": artifacts,
    }
    result["verdict"] = _verdict(result["ai_indicators"])
    return result


def write_reports(result: dict[str, Any], output_dir: str | Path) -> dict[str, str]:
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = Path(result["file"]["name"]).stem
    json_path = out_dir / f"{stem}-ai-image-detection-report.json"
    html_path = out_dir / f"{stem}-ai-image-detection-report.html"
    json_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    html_path.write_text(_html_report(result), encoding="utf-8")
    return {"json": str(json_path), "html": str(html_path)}


def _read_image_info(path: Path) -> dict[str, Any]:
    try:
        with Image.open(path) as image:
            return {
                "format": image.format,
                "mode": image.mode,
                "width": image.width,
                "height": image.height,
            }
    except Exception as exc:
        return {"error": str(exc)}


def _extract_metadata(data: bytes, path: Path) -> dict[str, Any]:
    metadata: dict[str, Any] = {
        "png_text": {},
        "jpeg_comments": [],
        "jpeg_app_segments": {},
        "pil_info": {},
        "xmp": [],
    }
    try:
        with Image.open(path) as image:
            for key, value in image.info.items():
                if isinstance(value, (str, int, float, bool)):
                    metadata["pil_info"][str(key)] = str(value)
    except Exception:
        pass

    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        metadata["png_text"] = _parse_png_text(data)
    if data.startswith(b"\xff\xd8"):
        jpeg = _parse_jpeg_segments(data)
        metadata["jpeg_comments"] = jpeg["comments"]
        metadata["jpeg_app_segments"] = jpeg["app_segments"]
        metadata["xmp"] = jpeg["xmp"]
    if b"<x:xmpmeta" in data or b"http://ns.adobe.com/xap/1.0/" in data:
        for sample in _find_text_windows(data, [b"<x:xmpmeta", b"http://ns.adobe.com/xap/1.0/"], 4000):
            metadata["xmp"].append(sample)
    return metadata


def _parse_png_text(data: bytes) -> dict[str, str]:
    chunks: dict[str, str] = {}
    offset = 8
    while offset + 12 <= len(data):
        length = struct.unpack(">I", data[offset : offset + 4])[0]
        chunk_type = data[offset + 4 : offset + 8]
        payload = data[offset + 8 : offset + 8 + length]
        offset += 12 + length
        try:
            if chunk_type == b"tEXt" and b"\x00" in payload:
                key, value = payload.split(b"\x00", 1)
                chunks[_decode(key)] = _decode(value)
            elif chunk_type == b"zTXt" and b"\x00" in payload:
                key, rest = payload.split(b"\x00", 1)
                if rest[:1] == b"\x00":
                    chunks[_decode(key)] = _decode(zlib.decompress(rest[1:]))
            elif chunk_type == b"iTXt" and b"\x00" in payload:
                parts = payload.split(b"\x00", 5)
                if len(parts) == 6:
                    key, compression_flag, _method, _language, _translated, text = parts
                    if compression_flag == b"\x01":
                        text = zlib.decompress(text)
                    chunks[_decode(key)] = _decode(text)
        except Exception:
            continue
        if chunk_type == b"IEND":
            break
    return chunks


def _parse_jpeg_segments(data: bytes) -> dict[str, Any]:
    offset = 2
    comments: list[str] = []
    app_segments: dict[str, str] = {}
    xmp: list[str] = []
    while offset + 4 < len(data):
        if data[offset] != 0xFF:
            offset += 1
            continue
        while offset < len(data) and data[offset] == 0xFF:
            offset += 1
        if offset >= len(data):
            break
        marker = data[offset]
        offset += 1
        if marker in {0xD9, 0xDA}:
            break
        if offset + 2 > len(data):
            break
        length = struct.unpack(">H", data[offset : offset + 2])[0]
        payload = data[offset + 2 : offset + length]
        offset += length
        if marker == 0xFE:
            comments.append(_decode(payload))
        elif 0xE0 <= marker <= 0xEF:
            name = f"APP{marker - 0xE0}"
            text = _decode(payload[:2048])
            app_segments[name] = text
            if b"xmp" in payload.lower() or b"<x:" in payload:
                xmp.append(_decode(payload))
    return {"comments": comments, "app_segments": app_segments, "xmp": xmp}


def _embedded_signals(data: bytes) -> dict[str, Any]:
    lowered = data.lower()
    c2pa_present = any(marker in lowered for marker in [b"c2pa", b"jumbf", b"contentauthenticity"])
    sample = ""
    if c2pa_present:
        sample = _find_text_windows(data, [b"c2pa", b"jumbf", b"contentauthenticity"], 240)[0]
    return {
        "c2pa_present": c2pa_present,
        "jumbf_present": b"jumbf" in lowered,
        "c2pa_sample": sample,
    }


def _collect_text_sources(metadata: dict[str, Any], data: bytes) -> list[dict[str, str]]:
    sources: list[dict[str, str]] = []
    for key, value in metadata.get("png_text", {}).items():
        sources.append({"source": "png_text", "key": key, "text": value})
    for key, value in metadata.get("pil_info", {}).items():
        sources.append({"source": "pil_info", "key": key, "text": value})
    for idx, value in enumerate(metadata.get("jpeg_comments", [])):
        sources.append({"source": "jpeg_comment", "key": str(idx), "text": value})
    for key, value in metadata.get("jpeg_app_segments", {}).items():
        sources.append({"source": "jpeg_app_segment", "key": key, "text": value})
    for idx, value in enumerate(metadata.get("xmp", [])):
        sources.append({"source": "xmp", "key": str(idx), "text": value})
    for idx, value in enumerate(_ascii_strings(data)):
        sources.append({"source": "binary_strings", "key": str(idx), "text": value})
    return sources


def _scan_ai_text_sources(sources: list[dict[str, str]]) -> list[dict[str, Any]]:
    indicators: list[dict[str, Any]] = []
    for source in sources:
        text = source["text"]
        for generator, pattern, kind, reason, confidence in AI_PATTERNS:
            match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
            if not match:
                continue
            indicators.append(
                {
                    "kind": kind,
                    "generator": generator,
                    "source": source["source"],
                    "key": source["key"],
                    "confidence": confidence,
                    "reason": reason,
                    "sample": _sample(text, match.start(), match.end()),
                }
            )
    return indicators


def _run_ocr(path: Path) -> dict[str, Any]:
    tesseract = shutil.which("tesseract")
    result: dict[str, Any] = {"ocr_available": bool(tesseract), "ocr_enabled": True, "matches": [], "text": ""}
    if not tesseract:
        result["error"] = "tesseract was not found on PATH"
        return result
    try:
        with Image.open(path) as image:
            image = image.convert("RGB")
            image.thumbnail((1800, 1800))
            with tempfile.TemporaryDirectory() as tmp:
                tmp_path = Path(tmp) / "ocr.png"
                image.save(tmp_path)
                completed = subprocess.run(
                    [tesseract, str(tmp_path), "stdout", "--psm", "6"],
                    check=False,
                    capture_output=True,
                    text=True,
                    timeout=20,
                )
        text = completed.stdout.strip()
        result["text"] = text
        for generator, pattern in VISIBLE_WATERMARK_PATTERNS:
            match = re.search(pattern, text, re.IGNORECASE)
            if match:
                result["matches"].append({"generator": generator, "text": _sample(text, match.start(), match.end())})
    except Exception as exc:
        result["error"] = str(exc)
    return result


def _write_frequency_artifact(path: Path, out_path: Path) -> bool:
    try:
        with Image.open(path) as image:
            gray = image.convert("L")
            gray.thumbnail((512, 512))
            arr = np.asarray(gray, dtype=np.float32)
            spectrum = np.log1p(np.abs(np.fft.fftshift(np.fft.fft2(arr))))
            spectrum -= spectrum.min()
            if spectrum.max() > 0:
                spectrum *= 255.0 / spectrum.max()
            Image.fromarray(spectrum.astype(np.uint8)).save(out_path)
        return True
    except Exception:
        return False


def _verdict(indicators: list[dict[str, Any]]) -> dict[str, Any]:
    if not indicators:
        return {
            "label": "no_ai_evidence",
            "score": 0,
            "summary": "没有发现可支持的 AI 水印、内容凭证或已知生成器元数据。",
        }
    score = max(int(item.get("confidence", 0)) for item in indicators)
    if any(item["kind"] in {"metadata", "content_credentials"} and item["confidence"] >= 70 for item in indicators):
        label = "strong_ai_evidence"
        summary = "发现强证据：元数据、内容凭证或嵌入式生成器字段指向 AI 生成/AI 合成内容。"
    else:
        label = "possible_ai_evidence"
        summary = "只发现弱证据或启发式线索，不能作为确定结论。"
    return {"label": label, "score": score, "summary": summary}


def _forensic_notes() -> list[str]:
    return [
        "本工具报告的是证据强弱，不等于绝对作者归属；元数据和可见水印都可能被删除或伪造。",
        "视觉/内容判断是人工或外部模型给出的疑似判断，应和硬证据分开看。",
        "私有隐形水印通常需要模型厂商的专用检测器，通用工具不能稳定提取。",
        "截图、社交平台压缩、格式转换经常会破坏元数据和水印信号。",
    ]


def _dedupe_indicators(indicators: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen = set()
    deduped = []
    for item in indicators:
        key = (item.get("kind"), item.get("generator"), item.get("source"), item.get("key"), item.get("sample"))
        if key in seen:
            continue
        seen.add(key)
        deduped.append(item)
    return deduped


def _ascii_strings(data: bytes) -> list[str]:
    strings = []
    for match in re.finditer(rb"[\x20-\x7e]{8,}", data):
        text = _decode(match.group(0))
        if any(token in text.lower() for token in ["prompt", "sampler", "steps", "c2pa", "firefly", "midjourney", "openai", "comfy", "dall", "stable"]):
            strings.append(text[:3000])
    return strings[:80]


def _find_text_windows(data: bytes, needles: list[bytes], window: int) -> list[str]:
    lowered = data.lower()
    windows = []
    for needle in needles:
        index = lowered.find(needle.lower())
        if index == -1:
            continue
        start = max(0, index - window // 2)
        end = min(len(data), index + window // 2)
        windows.append(_decode(data[start:end]))
    return windows or [""]


def _decode(value: bytes) -> str:
    for encoding in ("utf-8", "utf-16", "latin-1"):
        try:
            return value.decode(encoding, errors="ignore").replace("\x00", "").strip()
        except Exception:
            continue
    return repr(value)


def _sample(text: str, start: int, end: int, radius: int = 110) -> str:
    left = max(0, start - radius)
    right = min(len(text), end + radius)
    return re.sub(r"\s+", " ", text[left:right]).strip()


def _normalize_content_assessment(content_assessment: dict[str, Any] | None) -> dict[str, Any]:
    if not content_assessment:
        return {
            "label": "not_provided",
            "summary": "未提供视觉/内容疑似判断。",
            "notes": [],
        }
    label = str(content_assessment.get("label") or "not_provided")
    summary = str(content_assessment.get("summary") or _content_label_cn(label))
    raw_notes = content_assessment.get("notes") or []
    if isinstance(raw_notes, str):
        notes = [raw_notes]
    else:
        notes = [str(note) for note in raw_notes if str(note).strip()]
    return {"label": label, "summary": summary, "notes": notes}


def _html_report(result: dict[str, Any]) -> str:
    indicators = result.get("ai_indicators", [])
    rows = "\n".join(
        "<tr>"
        f"<td>{html.escape(_kind_cn(item.get('kind', '')))}</td>"
        f"<td>{html.escape(item.get('generator', ''))}</td>"
        f"<td>{html.escape(str(item.get('confidence', '')))}</td>"
        f"<td>{html.escape(_source_cn(item.get('source', '')))}</td>"
        f"<td>{html.escape(item.get('sample', ''))}</td>"
        "</tr>"
        for item in indicators
    )
    if not rows:
        rows = "<tr><td colspan=\"5\">没有发现 AI 相关证据。</td></tr>"
    metadata_json = html.escape(json.dumps(result.get("metadata", {}), ensure_ascii=False, indent=2))
    notes = "".join(f"<li>{html.escape(note)}</li>" for note in result.get("forensic_notes", []))
    verdict_label = _verdict_label_cn(result["verdict"]["label"])
    content = result.get("content_assessment") or _normalize_content_assessment(None)
    content_notes = "".join(f"<li>{html.escape(note)}</li>" for note in content.get("notes", []))
    if not content_notes:
        content_notes = "<li>没有记录额外的视觉疑似理由。</li>"
    c2pa = "发现" if result.get("embedded_signals", {}).get("c2pa_present") else "未发现"
    ocr = result.get("visible_watermarks", {})
    ocr_state = "已运行" if ocr.get("ocr_enabled") else "未运行"
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AI 图片检测报告 - {html.escape(result['file']['name'])}</title>
  <style>
    body {{ margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #17202a; background: #f6f8fb; }}
    main {{ max-width: 1080px; margin: 0 auto; padding: 36px 20px; }}
    h1 {{ margin: 0 0 10px; font-size: 30px; }}
    .summary {{ padding: 18px; background: #fff; border: 1px solid #d9e1ec; border-radius: 8px; }}
    .label {{ display: inline-block; padding: 5px 9px; border-radius: 5px; background: #14213d; color: #fff; font-weight: 700; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 22px; background: #fff; }}
    th, td {{ text-align: left; vertical-align: top; border: 1px solid #d9e1ec; padding: 10px; font-size: 14px; }}
    th {{ background: #eaf0f7; }}
    pre {{ overflow: auto; background: #101820; color: #f7f9fb; padding: 14px; border-radius: 8px; }}
  </style>
</head>
<body>
<main>
  <h1>AI 图片检测报告</h1>
  <section class="summary">
    <p><strong>文件：</strong> {html.escape(result['file']['path'])}</p>
    <p><strong>图片：</strong> {html.escape(str(result.get('image', {}).get('width', '未知')))} x {html.escape(str(result.get('image', {}).get('height', '未知')))}，格式 {html.escape(str(result.get('image', {}).get('format', '未知')))}</p>
    <p><strong>结论：</strong> <span class="label">{html.escape(verdict_label)}</span> 分数 {html.escape(str(result['verdict']['score']))}</p>
    <p>{html.escape(result['verdict']['summary'])}</p>
    <p><strong>C2PA / JUMBF：</strong> {c2pa}　<strong>OCR：</strong> {ocr_state}</p>
  </section>
  <h2>证据</h2>
  <table>
    <thead><tr><th>类型</th><th>识别对象</th><th>置信分</th><th>来源</th><th>证据片段</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <h2>视觉/内容判断</h2>
  <section class="summary">
    <p><strong>判断：</strong> <span class="label">{html.escape(_content_label_cn(content.get('label', 'not_provided')))}</span></p>
    <p>{html.escape(content.get('summary', ''))}</p>
    <ul>{content_notes}</ul>
  </section>
  <h2>限制说明</h2>
  <ul>{notes}</ul>
  <h2>元数据</h2>
  <pre>{metadata_json}</pre>
</main>
</body>
</html>
"""


def _verdict_label_cn(label: str) -> str:
    return {
        "strong_ai_evidence": "强证据：AI 生成/AI 合成",
        "possible_ai_evidence": "疑似：只有弱证据",
        "no_ai_evidence": "未发现 AI 证据",
    }.get(label, label)


def _content_label_cn(label: str) -> str:
    return {
        "likely_ai": "高度疑似 AI",
        "possible_ai": "疑似 AI",
        "unclear": "无法判断",
        "likely_not_ai": "不像 AI",
        "not_provided": "未提供视觉判断",
    }.get(label, label)


def _kind_cn(kind: str) -> str:
    return {
        "metadata": "元数据",
        "content_credentials": "内容凭证",
        "visible_watermark": "可见水印",
    }.get(kind, kind)


def _source_cn(source: str) -> str:
    return {
        "png_text": "PNG 文本块",
        "pil_info": "图片信息",
        "xmp": "XMP 元数据",
        "binary_scan": "二进制扫描",
        "ocr": "OCR 识别",
        "jpeg_comment": "JPEG 注释",
        "jpeg_app_segment": "JPEG APP 段",
        "binary_strings": "二进制文本",
    }.get(source, source)
